name: "{tool-name} PR Annotator"
description: "Annotate pull requests with {tool-name} errors detected during CI"
author: "Joe Young"
runs:
  using: "composite"
  steps:
    - run: echo "::add-matcher::${{ github.action_path }}/problem-matcher.json"
      shell: bash
